name: VoicePingIOSAndroidOfflineSpeechTranslation
options:
  bundleIdPrefix: com.voiceping
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE: false
    SUPPORTS_MAC_DESIGNED_FOR_IPAD: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false

configs:
  Debug: debug
  Release: release

packages:
  swift-collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.0"
  SherpaOnnxKit:
    path: LocalPackages/SherpaOnnxKit

targets:
  OfflineTranscription:
    type: application
    platform: iOS
    sources:
      - path: OfflineTranscription
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.translate
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: "YES"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
        INFOPLIST_KEY_CFBundleDisplayName: "VoicePing Offline Translate"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationAllButUpsideDown"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "This app needs microphone access to record and transcribe your speech."
    dependencies:
      - package: SherpaOnnxKit
        product: SherpaOnnxKit

  OfflineTranscriptionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OfflineTranscriptionTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.translate-tests
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: OfflineTranscription

  OfflineTranscriptionUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OfflineTranscriptionUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.translate-uitests
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: OfflineTranscription

  OfflineTranscriptionCITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OfflineTranscriptionCITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceping.translate-ci-tests
        GENERATE_INFOPLIST_FILE: "YES"
    dependencies:
      - target: OfflineTranscription

schemes:
  OfflineTranscription:
    build:
      targets:
        OfflineTranscription: all
    test:
      targets:
        - name: OfflineTranscriptionTests
  OfflineTranscriptionCI:
    build:
      targets:
        OfflineTranscription: all
        OfflineTranscriptionCITests: all
    test:
      targets:
        - name: OfflineTranscriptionCITests
  OfflineTranscriptionE2ECI:
    build:
      targets:
        OfflineTranscription: all
        OfflineTranscriptionUITests: all
    test:
      targets:
        - name: OfflineTranscriptionUITests
